name: Hola Mundo

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Make script executable
      run: chmod +x ./Hola.bash

    - name: Run Hola Mundo script
      run: ./Hola.bash
